name: Validator_Pytest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  in_network_rates_schema_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
      -
        name: compile validator
        run: |
          g++ schemavalidator.cpp -o validator
      -
        name: install pytest
        working-directory: ./tests
        run: pip install -U pytest
      -
        name: run in network tests
        working-directory: ./tests/in network/
        run: pytest

  allowed_amounts_schema_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
      -
        name: compile validator
        run: |
          g++ schemavalidator.cpp -o validator
      -
        name: install pytest
        working-directory: ./tests
        run: |
          pip install -U pytest   
      -
        name: run allowed amounts tests
        working-directory: ./tests/allowed amounts
        run: |
          pytest
          
  prescription_drug_schema_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
      -
        name: compile validator
        run: |
          g++ schemavalidator.cpp -o validator
      -
        name: install pytest
        working-directory: ./tests
        run: |
          pip install -U pytest   
      -
        name: run allowed amounts tests
        working-directory: ./tests/prescription drugs
        run: pytest