name: Validator_Pytest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  in_network_rates_schema_test:
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
      -
        name: install pytest
        working-directory: ./tests
        run: pip install -U pytest
      -
        name: compile
        run: |
          g++ schemavalidator.cpp -o validator
      -
        name: test schemas
        working-directory: ./tests
        run: pytest test_in_network_rates_schema.py

  allowed_amounts_schema_test:
    runs-on: ubuntu-latest

    steps:
      -
        name: checkout repository
        uses: actions/checkout@v2
      -
        name: install pytest
        working-directory: ./tests
        run: pip install -U pytest
      -
        name: compile
        run: |
          g++ schemavalidator.cpp -o validator
      -
        name: test schemas
        working-directory: ./tests
        run: pytest test_allowed_amounts_schema.py
